# Generated by Django 5.0.6 on 2024-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='blockchain_address',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
