# Generated by Django 5.0.6 on 2024-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='blockchain_address',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
